import argparse
import os
from pathlib import Path

import psycopg
from dotenv import load_dotenv
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict
from psycopg.errors import DuplicateDatabase

load_dotenv(Path(__file__).resolve().parent / ".env")

DATABASE_NAME = os.getenv("DATABASE_NAME", "symptoms_tracker_db")
SCHEMA_MIGRATIONS = (
    "ALTER TABLE patients ADD COLUMN IF NOT EXISTS care_team_label TEXT",
    "ALTER TABLE daily_summary_logs ADD COLUMN IF NOT EXISTS stiffness_time TEXT",
    "ALTER TABLE daily_summary_logs ADD COLUMN IF NOT EXISTS morning_stiffness_degree SMALLINT",
    "ALTER TABLE daily_summary_logs ADD COLUMN IF NOT EXISTS evening_stiffness_degree SMALLINT",
    "ALTER TABLE daily_summary_logs ADD COLUMN IF NOT EXISTS evening_stiffness_mins INTEGER",
    "ALTER TABLE daily_summary_logs ADD COLUMN IF NOT EXISTS exercise_done_bool BOOLEAN",
    "ALTER TABLE daily_summary_logs ADD COLUMN IF NOT EXISTS medication_taken_bool BOOLEAN",
    "ALTER TABLE daily_summary_logs ADD COLUMN IF NOT EXISTS medication_frequency SMALLINT",
)
PAIN_INTENSITY_SCALE = (
    (0, None, "No pain; completely normal movement."),
    (1, "Barely Noticeable", "Minor ache; does not affect posture or movement."),
    (2, "Minor", "Can be ignored; slightly effects posture and walking."),
    (
        3,
        "Mild",
        "Noticeable; causes highly noticable changes in sitting or walking posture.",
    ),
    (4, "Distracting", "Cannot be ignored; requires changing positions frequently."),
    (
        5,
        "Moderate",
        "Interferes with focus; actively avoids prolonged sitting or driving.",
    ),
    (6, "Distressing", "Limits basic activities; short walk or standing is painful."),
    (
        7,
        "Severe",
        "Majorly limits mobility; struggles to find a comfortable lying position.",
    ),
    (
        8,
        "Intense",
        "Severe limits; basic self-care (showering or dressing) triggers sharp spikes.",
    ),
    (
        9,
        "Unbearable",
        "Agonising; unable to sit or stand or sleep regardless of position.",
    ),
    (
        10,
        "Emergency",
        "Worst imaginable; requires immediate medical attention or immobilization.",
    ),
)
PAIN_TYPES = (
    ("DULL", "Dull ache"),
    ("SHARP", "Sharp pain"),
    ("FATIGUE", "Muscle fatigue"),
    ("STIFF", "Stiffness"),
    ("BURN", "Burning"),
    ("THROB", "Throbbing"),
    ("SPASM", "Muscle spasm"),
    ("PULL", "Pulling sensation"),
    ("PRESS", "Pressure sensation"),
)

TABLES = (
    """
    CREATE TABLE IF NOT EXISTS patients (
        patient_id TEXT PRIMARY KEY,
        care_team_label TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pain_intensity_scale (
        score SMALLINT PRIMARY KEY CHECK (score BETWEEN 0 AND 10),
        descriptor TEXT,
        functional_meaning TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pain_types (
        code TEXT PRIMARY KEY,
        meaning TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS daily_summary_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        patient_id TEXT NOT NULL REFERENCES patients(patient_id),
        entry_date DATE NOT NULL,
        sleep_hours NUMERIC(4, 2) CHECK (sleep_hours BETWEEN 0 AND 24),
        sleep_quality SMALLINT CHECK (sleep_quality BETWEEN 0 AND 10),
        stiffness_time TEXT,
        morning_stiffness_degree SMALLINT CHECK (
            morning_stiffness_degree BETWEEN 0 AND 10
            OR morning_stiffness_degree IS NULL
        ),
        morning_pain SMALLINT REFERENCES pain_intensity_scale(score),
        afternoon_pain SMALLINT REFERENCES pain_intensity_scale(score),
        evening_pain SMALLINT REFERENCES pain_intensity_scale(score),
        night_pain SMALLINT REFERENCES pain_intensity_scale(score),
        morning_stiffness_mins INTEGER CHECK (morning_stiffness_mins >= 0),
        evening_stiffness_degree SMALLINT CHECK (
            evening_stiffness_degree BETWEEN 0 AND 10
            OR evening_stiffness_degree IS NULL
        ),
        evening_stiffness_mins INTEGER CHECK (evening_stiffness_mins >= 0),
        total_walking_mins INTEGER CHECK (total_walking_mins >= 0),
        sitting_hours NUMERIC(6, 2) CHECK (sitting_hours >= 0),
        lumbar_support_type_seat_bool BOOLEAN,
        standing_mins INTEGER CHECK (standing_mins >= 0),
        exercise_done_bool BOOLEAN,
        exercise_minutes INTEGER CHECK (exercise_minutes >= 0),
        medication_taken_bool BOOLEAN,
        medication_name TEXT,
        medication_frequency SMALLINT CHECK (medication_frequency BETWEEN 1 AND 6),
        abnormal_fatigue_bool BOOLEAN,
        adequate_hydration_bool BOOLEAN,
        exhausting_day_bool BOOLEAN,
        overall_description TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (patient_id, entry_date)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS daily_summary_exercises (
        daily_summary_id BIGINT NOT NULL
            REFERENCES daily_summary_logs(id) ON DELETE CASCADE,
        exercise_type TEXT NOT NULL,
        PRIMARY KEY (daily_summary_id, exercise_type)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS daily_summary_pain_regions (
        daily_summary_id BIGINT NOT NULL
            REFERENCES daily_summary_logs(id) ON DELETE CASCADE,
        pain_region TEXT NOT NULL,
        PRIMARY KEY (daily_summary_id, pain_region)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS activity_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        patient_id TEXT NOT NULL REFERENCES patients(patient_id),
        entry_date DATE NOT NULL,
        time_of_day TIME NOT NULL,
        activity_type TEXT NOT NULL,
        duration_mins INTEGER CHECK (duration_mins >= 0),
        repetitions INTEGER CHECK (repetitions >= 0),
        pain_before SMALLINT REFERENCES pain_intensity_scale(score),
        pain_during SMALLINT REFERENCES pain_intensity_scale(score),
        pain_after_30mins SMALLINT REFERENCES pain_intensity_scale(score),
        pain_after_2hrs SMALLINT REFERENCES pain_intensity_scale(score),
        source_record_key TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (duration_mins IS NOT NULL OR repetitions IS NOT NULL),
        UNIQUE (patient_id, source_record_key)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pain_characteristics (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        patient_id TEXT NOT NULL REFERENCES patients(patient_id),
        entry_date DATE NOT NULL,
        primary_location TEXT,
        secondary_location TEXT,
        pain_intensity SMALLINT REFERENCES pain_intensity_scale(score),
        pain_intensity_2 SMALLINT REFERENCES pain_intensity_scale(score),
        radiation BOOLEAN,
        pinpoint_or_diffuse TEXT
            CHECK (pinpoint_or_diffuse IN ('Pinpoint', 'Diffuse')
                   OR pinpoint_or_diffuse IS NULL),
        deep_or_surface TEXT
            CHECK (deep_or_surface IN ('Deep', 'Surface') OR deep_or_surface IS NULL),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (patient_id, entry_date)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pain_characteristic_types (
        pain_characteristic_id BIGINT NOT NULL
            REFERENCES pain_characteristics(id) ON DELETE CASCADE,
        pain_type_code TEXT NOT NULL REFERENCES pain_types(code),
        PRIMARY KEY (pain_characteristic_id, pain_type_code)
    )
    """,
)
RLS_POLICIES = (
    (
        "patients_owner_access",
        "patients",
        "patient_id = current_setting('app.current_user_id', true)",
    ),
    (
        "daily_summary_logs_owner_access",
        "daily_summary_logs",
        "patient_id = current_setting('app.current_user_id', true)",
    ),
    (
        "activity_logs_owner_access",
        "activity_logs",
        "patient_id = current_setting('app.current_user_id', true)",
    ),
    (
        "pain_characteristics_owner_access",
        "pain_characteristics",
        "patient_id = current_setting('app.current_user_id', true)",
    ),
    (
        "daily_summary_pain_regions_owner_access",
        "daily_summary_pain_regions",
        "EXISTS (SELECT 1 FROM daily_summary_logs AS owner_log "
        "WHERE owner_log.id = daily_summary_id "
        "AND owner_log.patient_id = current_setting('app.current_user_id', true))",
    ),
    (
        "daily_summary_exercises_owner_access",
        "daily_summary_exercises",
        "EXISTS (SELECT 1 FROM daily_summary_logs AS owner_log "
        "WHERE owner_log.id = daily_summary_id "
        "AND owner_log.patient_id = current_setting('app.current_user_id', true))",
    ),
    (
        "pain_characteristic_types_owner_access",
        "pain_characteristic_types",
        "EXISTS (SELECT 1 FROM pain_characteristics AS owner_log "
        "WHERE owner_log.id = pain_characteristic_id "
        "AND owner_log.patient_id = current_setting('app.current_user_id', true))",
    ),
)


def connection_parameters(database_name: str) -> dict[str, str]:
    connection_info = os.getenv("CONN_INFO")
    if not connection_info:
        raise ValueError("Set CONN_INFO in the environment or .env file.")
    parameters = conninfo_to_dict(connection_info)
    parameters["dbname"] = database_name
    return parameters


def create_database() -> None:
    maintenance_parameters = connection_parameters("postgres")
    with psycopg.connect(**maintenance_parameters, autocommit=True) as connection:
        try:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL("CREATE DATABASE {}").format(sql.Identifier(DATABASE_NAME))
                )
            print(f"Created database {DATABASE_NAME!r}.")
        except DuplicateDatabase:
            print(f"Database {DATABASE_NAME!r} already exists.")


def create_tables_and_reference_data(cursor: psycopg.Cursor) -> None:
    for statement in TABLES:
        cursor.execute(statement)

    for statement in SCHEMA_MIGRATIONS:
        cursor.execute(statement)

    for table_name in (
        "patients",
        "pain_intensity_scale",
        "pain_types",
        "daily_summary_logs",
        "daily_summary_exercises",
        "daily_summary_pain_regions",
        "activity_logs",
        "pain_characteristics",
        "pain_characteristic_types",
    ):
        cursor.execute(
            sql.SQL("ALTER TABLE {} ENABLE ROW LEVEL SECURITY").format(
                sql.Identifier(table_name)
            )
        )

    for policy_name, table_name, predicate in RLS_POLICIES:
        policy = sql.Identifier(policy_name)
        table = sql.Identifier(table_name)
        cursor.execute(sql.SQL("DROP POLICY IF EXISTS {} ON {}").format(policy, table))
        cursor.execute(
            sql.SQL("CREATE POLICY {} ON {} FOR ALL USING ({}) WITH CHECK ({})").format(
                policy,
                table,
                sql.SQL(predicate),
                sql.SQL(predicate),
            )
        )

    cursor.executemany(
        """
        INSERT INTO pain_intensity_scale (score, descriptor, functional_meaning)
        VALUES (%s, %s, %s)
        ON CONFLICT (score) DO UPDATE SET
            descriptor = EXCLUDED.descriptor,
            functional_meaning = EXCLUDED.functional_meaning
        """,
        PAIN_INTENSITY_SCALE,
    )
    cursor.executemany(
        """
        INSERT INTO pain_types (code, meaning)
        VALUES (%s, %s)
        ON CONFLICT (code) DO UPDATE SET meaning = EXCLUDED.meaning
        """,
        PAIN_TYPES,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Initialize the PainMetrics database.")
    parser.add_argument(
        "--schema-only",
        action="store_true",
        help="Initialize tables in the configured database without creating a database.",
    )
    arguments = parser.parse_args()

    if not arguments.schema_only:
        create_database()
    with psycopg.connect(**connection_parameters(DATABASE_NAME)) as connection:
        with connection.cursor() as cursor:
            create_tables_and_reference_data(cursor)
    print(f"Database {DATABASE_NAME!r} is ready.")


if __name__ == "__main__":
    main()
